%YAML:1.0
---

Camera.type: "PinHole"
File.version: "1.0"

Camera1.fx: 579.488269
Camera1.fy: 579.488269
Camera1.cx: 342.132988
Camera1.cy: 255.806288

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera2.fx: 579.488269
Camera2.fy: 579.488269
Camera2.cx: 342.132988
Camera2.cy: 255.806288

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0

Camera.width: 688
Camera.height: 512
Camera.fps: 30
Camera.RGB: 1

Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1,0,0,-0.2003247161505525,
         0,1,0,0,
         0,0,1,0,
         0,0,0,1]

Stereo.ThDepth: 60.0

ORBextractor.nFeatures: 2000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 5

Viewer: 0
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
